name: Lint

"on":
  pull_request:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@1c37ad07a6a961277cf70c0d37d6f313000f5884 # v10.3.0

      - name: Create virtual environment
        run: |
          make .venv

      - name: Run lint, format, and type-check
        run: |
          make check-py

  shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run shellcheck
        run: |
          make shellcheck
